server:
  address: ":9876"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  logger:
    path: "/var/log/gf-app/sql"
    level: "all"
    stdout: true
  default:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/could_customer_server"
    debug: true

jwt:
  realm: cloud_customer_service
  secretKey: yhblsqtchblqqxmbdwwlc

redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:      1

  msg-notification:
    address:     127.0.0.1:6379
    db:          2


ipDb: D:\code\cloudCustomer\cloud_customer_service\resource\GeoLite2-Country.mmdb