// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cloudCustomerService/internal/dao/internal"
)

// internalChatSupportsDao is internal type for wrapping internal DAO implements.
type internalChatSupportsDao = *internal.ChatSupportsDao

// chatSupportsDao is the data access object for table chat_supports.
// You can define custom methods on it to extend its functionality as you wish.
type chatSupportsDao struct {
	internalChatSupportsDao
}

var (
	// ChatSupports is globally public accessible object for table chat_supports operations.
	ChatSupports = chatSupportsDao{
		internal.NewChatSupportsDao(),
	}
)

// Fill with you ideas below.
