// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cloudCustomerService/internal/dao/internal"
)

// internalCustomerServiceAgentsDao is internal type for wrapping internal DAO implements.
type internalCustomerServiceAgentsDao = *internal.CustomerServiceAgentsDao

// customerServiceAgentsDao is the data access object for table customer_service_agents.
// You can define custom methods on it to extend its functionality as you wish.
type customerServiceAgentsDao struct {
	internalCustomerServiceAgentsDao
}

var (
	// CustomerServiceAgents is globally public accessible object for table customer_service_agents operations.
	CustomerServiceAgents = customerServiceAgentsDao{
		internal.NewCustomerServiceAgentsDao(),
	}
)

// Fill with you ideas below.
