// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cloudCustomerService/internal/dao/internal"
)

// internalMerchantGroupDao is internal type for wrapping internal DAO implements.
type internalMerchantGroupDao = *internal.MerchantGroupDao

// merchantGroupDao is the data access object for table merchant_group.
// You can define custom methods on it to extend its functionality as you wish.
type merchantGroupDao struct {
	internalMerchantGroupDao
}

var (
	// MerchantGroup is globally public accessible object for table merchant_group operations.
	MerchantGroup = merchantGroupDao{
		internal.NewMerchantGroupDao(),
	}
)

// Fill with you ideas below.
