// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cloudCustomerService/internal/dao/internal"
)

// internalMessageTemplatesDao is internal type for wrapping internal DAO implements.
type internalMessageTemplatesDao = *internal.MessageTemplatesDao

// messageTemplatesDao is the data access object for table message_templates.
// You can define custom methods on it to extend its functionality as you wish.
type messageTemplatesDao struct {
	internalMessageTemplatesDao
}

var (
	// MessageTemplates is globally public accessible object for table message_templates operations.
	MessageTemplates = messageTemplatesDao{
		internal.NewMessageTemplatesDao(),
	}
)

// Fill with you ideas below.
