// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cloudCustomerService/internal/dao/internal"
)

// internalTicketsDao is internal type for wrapping internal DAO implements.
type internalTicketsDao = *internal.TicketsDao

// ticketsDao is the data access object for table tickets.
// You can define custom methods on it to extend its functionality as you wish.
type ticketsDao struct {
	internalTicketsDao
}

var (
	// Tickets is globally public accessible object for table tickets operations.
	Tickets = ticketsDao{
		internal.NewTicketsDao(),
	}
)

// Fill with you ideas below.
